[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["UniversalRegistrarRenewalWithOriginalReferrerEvent", "UniversalRegistrarRenewalWithAdditionalReferrerEvent", "UniversalRegistrarRenewalWithSimpleReferrerEvent"]

# Mainnet forking configuration
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

[fmt]
line_length = 140

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
