name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rust-circuit:
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - uses: actions/checkout@v3
      - name: Build rust client
        working-directory: ./circuit
        run: |
          cargo build --verbose
      - name: Test rust client
        working-directory: ./circuit
        run: |
          export PROVIDER_URI=${{ secrets.PROVIDER_URI_SEPOLIA }}
          cargo test